// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteMain.Database;

namespace WebsiteMain.Migrations
{
    [DbContext(typeof(AndrewBoundsDatabaseModel))]
    partial class AndrewBoundsDatabaseModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CardGameData.CardGame", b =>
                {
                    b.Property<int>("GameNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstGuess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LastCard")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("Winner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinsInARow")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameNumber");

                    b.ToTable("CardGames");
                });

            modelBuilder.Entity("CardGameData.CardGuess", b =>
                {
                    b.Property<int>("GuessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Card")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardGameGameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GuessedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuessId");

                    b.HasIndex("CardGameGameNumber");

                    b.ToTable("CardGuess");
                });

            modelBuilder.Entity("CardGameData.CardGuess", b =>
                {
                    b.HasOne("CardGameData.CardGame", null)
                        .WithMany("Guesses")
                        .HasForeignKey("CardGameGameNumber");
                });

            modelBuilder.Entity("CardGameData.CardGame", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
